{
 "title": "Kafka cluster metrics",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": "label_values(kafka_cluster_partition_value, job)"
   }
  ]
 },
 "panels": [
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bytes in per second summary",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "  rate(kafka_server_brokertopicmetrics_count{name=\"BytesInPerSec\", topic=\"\", job=~\"$job\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Bytes out per second summary",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_count{name=\"BytesOutPerSec\", topic=\"\", job=~\"$job\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Messages in per second summary",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_count{name=\"MessagesInPerSec\", topic=\"\", job=~\"$job\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "BytesRejectedPerSec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_count{name=\"BytesRejectedPerSec\", topic=\"\", job=~\"$job\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ReplicationBytesInPerSec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_count{name=\"ReplicationBytesInPerSec\", topic=\"\", job=~\"$job\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ReplicationBytesOutPerSec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_count{name=\"ReplicationBytesOutPerSec\", topic=\"\", job=~\"$job\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "TotalProduceRequestsPerSec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_count{name=\"TotalProduceRequestsPerSec\", topic=\"\", job=~\"$job\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "TotalFetchRequestsPerSec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_count{name=\"TotalFetchRequestsPerSec\", topic=\"\", job=~\"$job\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Bytes in per second by topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_count{name=\"BytesInPerSec\", topic!=\"\", job=~\"$job\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes out per second by topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_count{name=\"BytesOutPerSec\", topic!=\"\", job=~\"$job\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages in per second per topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_count{name=\"MessagesInPerSec\", topic!=\"\", job=~\"$job\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Produce requests rate per topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_count{name=\"TotalProduceRequestsPerSec\", topic!=\"\", job=~\"$job\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Fetch requests rate per topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_count{name=\"TotalFetchRequestsPerSec\", topic!=\"\", job=~\"$job\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Produce  total ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_99thpercentile{name=\"TotalTimeMs\", request=\"Produce\", job=~\"$job\"}",
     "legendFormat": "{{pod}} 99th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_95thpercentile{name=\"TotalTimeMs\", request=\"Produce\", job=~\"$job\"}",
     "legendFormat": "{{pod}} 95th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_75thpercentile{name=\"TotalTimeMs\", request=\"Produce\", job=~\"$job\"}",
     "legendFormat": "{{pod}} 75th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_50thpercentile{name=\"TotalTimeMs\", request=\"Produce\", job=~\"$job\"}",
     "legendFormat": "{{pod}} 50th percentile"
    }
   ]
  },
  {
   "title": "FetchConsume total ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_99thpercentile{name=\"TotalTimeMs\", request=\"FetchConsumer\", job=~\"$job\"}",
     "legendFormat": "{{pod}} 99th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_95thpercentile{name=\"TotalTimeMs\", request=\"FetchConsumer\", job=~\"$job\"}",
     "legendFormat": "{{pod}} 95th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_75thpercentile{name=\"TotalTimeMs\", request=\"FetchConsumer\", job=~\"$job\"}",
     "legendFormat": "{{pod}} 75th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_50thpercentile{name=\"TotalTimeMs\", request=\"FetchConsumer\", job=~\"$job\"}",
     "legendFormat": "{{pod}} 50th percentile"
    }
   ]
  },
  {
   "title": "Produce  local time  ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_99thpercentile{name=\"LocalTimeMs\", request=\"Produce\", job=~\"$job\"}",
     "legendFormat": "{{pod}} 99th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_95thpercentile{name=\"LocalTimeMs\", request=\"Produce\", job=~\"$job\"}",
     "legendFormat": "{{pod}} 95th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_75thpercentile{name=\"LocalTimeMs\", request=\"Produce\", job=~\"$job\"}",
     "legendFormat": "{{pod}} 75th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_50thpercentile{name=\"LocalTimeMs\", request=\"Produce\", job=~\"$job\"}",
     "legendFormat": "{{pod}} 50th percentile"
    }
   ]
  },
  {
   "title": "FetchConsume local ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_99thpercentile{name=\"LocalTimeMs\", request=\"FetchConsumer\", job=~\"$job\"}",
     "legendFormat": "{{pod}} 99th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_95thpercentile{name=\"LocalTimeMs\", request=\"FetchConsumer\", job=~\"$job\"}",
     "legendFormat": "{{pod}} 95th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_75thpercentile{name=\"LocalTimeMs\", request=\"FetchConsumer\", job=~\"$job\"}",
     "legendFormat": "{{pod}} 75th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_50thpercentile{name=\"LocalTimeMs\", request=\"FetchConsumer\", job=~\"$job\"}",
     "legendFormat": "{{pod}} 50th percentile"
    }
   ]
  },
  {
   "title": "Produce  remote time  ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_99thpercentile{name=\"RemoteTimeMs\", request=\"Produce\", job=~\"$job\"}",
     "legendFormat": "{{pod}} 99th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_95thpercentile{name=\"RemoteTimeMs\", request=\"Produce\", job=~\"$job\"}",
     "legendFormat": "{{pod}} 95th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_75thpercentile{name=\"RemoteTimeMs\", request=\"Produce\", job=~\"$job\"}",
     "legendFormat": "{{pod}} 75th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_50thpercentile{name=\"RemoteTimeMs\", request=\"Produce\", job=~\"$job\"}",
     "legendFormat": "{{pod}} 50th percentile"
    }
   ]
  },
  {
   "title": "FetchConsume remote ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_99thpercentile{name=\"RemoteTimeMs\", request=\"FetchConsumer\", job=~\"$job\"}",
     "legendFormat": "{{pod}} 99th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_95thpercentile{name=\"RemoteTimeMs\", request=\"FetchConsumer\", job=~\"$job\"}",
     "legendFormat": "{{pod}} 95th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_75thpercentile{name=\"RemoteTimeMs\", request=\"FetchConsumer\", job=~\"$job\"}",
     "legendFormat": "{{pod}} 75th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_50thpercentile{name=\"RemoteTimeMs\", request=\"FetchConsumer\", job=~\"$job\"}",
     "legendFormat": "{{pod}} 50th percentile"
    }
   ]
  },
  {
   "title": "Network Requestmetrics OffsetCommit TotalMs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_999thpercentile{job=\"$job\", request=\"OffsetCommit\", name=\"TotalTimeMs\"}",
     "legendFormat": "{{pod}} 999th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_99thpercentile{job=\"$job\", request=\"OffsetCommit\", name=\"TotalTimeMs\"}",
     "legendFormat": "{{pod}} 99th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_95thpercentile{job=\"$job\", request=\"OffsetCommit\", name=\"TotalTimeMs\"}",
     "legendFormat": "{{pod}} 95th percentile"
    }
   ]
  },
  {
   "title": "Network Requestmetrics OffsetCommit LocalTimeMs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_999thpercentile{job=\"$job\", request=\"OffsetCommit\", name=\"LocalTimeMs\"}",
     "legendFormat": "{{pod}} 999th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_99thpercentile{job=\"$job\", request=\"OffsetCommit\", name=\"LocalTimeMs\"}",
     "legendFormat": "{{pod}} 99th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_95thpercentile{job=\"$job\", request=\"OffsetCommit\", name=\"LocalTimeMs\"}",
     "legendFormat": "{{pod}} 95th percentile"
    }
   ]
  },
  {
   "title": "Network Requestmetrics OffsetCommit RemoteTimeMs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_999thpercentile{job=\"$job\", request=\"OffsetCommit\", name=\"RemoteTimeMs\"}",
     "legendFormat": "{{pod}} 999th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_99thpercentile{job=\"$job\", request=\"OffsetCommit\", name=\"RemoteTimeMs\"}",
     "legendFormat": "{{pod}} 99th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_95thpercentile{job=\"$job\", request=\"OffsetCommit\", name=\"RemoteTimeMs\"}",
     "legendFormat": "{{pod}} 95th percentile"
    }
   ]
  },
  {
   "title": "Network Requestmetrics OffsetCommit ThrottleTimeMs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_999thpercentile{job=\"$job\", request=\"OffsetCommit\", name=\"ThrottleTimeMs\"}",
     "legendFormat": "{{pod}} 999th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_99thpercentile{job=\"$job\", request=\"OffsetCommit\", name=\"ThrottleTimeMs\"}",
     "legendFormat": "{{pod}} 99th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_95thpercentile{job=\"$job\", request=\"OffsetCommit\", name=\"ThrottleTimeMs\"}",
     "legendFormat": "{{pod}} 95th percentile"
    }
   ]
  },
  {
   "title": "Network Requestmetrics OffsetCommit RequestQueueTimeMs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_999thpercentile{job=\"$job\", request=\"OffsetCommit\", name=\"RequestQueueTimeMs\"}",
     "legendFormat": "{{pod}} 999th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_99thpercentile{job=\"$job\", request=\"OffsetCommit\", name=\"RequestQueueTimeMs\"}",
     "legendFormat": "{{pod}} 99th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_95thpercentile{job=\"$job\", request=\"OffsetCommit\", name=\"RequestQueueTimeMs\"}",
     "legendFormat": "{{pod}} 95th percentile"
    }
   ]
  },
  {
   "title": "Network Requestmetrics OffsetCommit ResponseQueueTimeMs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_999thpercentile{job=\"$job\", request=\"OffsetCommit\", name=\"ResponseQueueTimeMs\"}",
     "legendFormat": "{{pod}} 999th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_99thpercentile{job=\"$job\", request=\"OffsetCommit\", name=\"ResponseQueueTimeMs\"}",
     "legendFormat": "{{pod}} 99th percentile"
    },
    {
     "expr": "kafka_network_requestmetrics_95thpercentile{job=\"$job\", request=\"OffsetCommit\", name=\"ResponseQueueTimeMs\"}",
     "legendFormat": "{{pod}} 95th percentile"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "OfflinePartitionsCount",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_value{name=\"OfflinePartitionsCount\", job=~\"$job\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "UnderReplicatedPartitions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_value{name=\"UnderReplicatedPartitions\", job=~\"$job\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ActiveControllerCount",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_value{name=\"ActiveControllerCount\", job=~\"$job\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "FailedProduceRequestsPerSec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_count{name=\"FailedProduceRequestsPerSec\", job=~\"$job\", topic=\"\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "FailedFetchRequestsPerSec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_count{name=\"FailedFetchRequestsPerSec\", job=~\"$job\", topic=\"\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}