kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 20Gi

alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by:
        - alertname
        - job
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 5m
      receiver: 'null'
      routes:
        - match:
            alertname: DeadMansSwitch
          receiver: 'null'
    receivers:
      - name: 'null'

grafana:
  persistence:
    enabled: true